Update operators.py
line 335 had reference to operator_idxs that caused error 
```
  File "/home/exouser/miniforge3/lib/python3.10/site-packages/torchbiggraph/regularizers.py", line 73, in forward_dynamic
    operator_params = operator.get_operator_params_for_reg(rel_idxs)
  File "/home/exouser/miniforge3/lib/python3.10/site-packages/torchbiggraph/operators.py", line 335, in get_operator_params_for_reg
    return torch.sqrt(self.real[operator_idxs] ** 2 + self.imag[operator_idxs] ** 2)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)
Traceback (most recent call last):
  File "/home/exouser/CLEAN/PyTorch-BigGraph/torchbiggraph/examples/fb15k.py", line 108, in <module>

```
Clearly 0 is not an ideal choice but for a single GPU seems OK